import js from '@eslint/js';
import prettier from 'eslint-config-prettier';

export default [
    { ignores: ['dist/', 'node_modules/'] },
    js.configs.recommended,
    prettier,
    {
        languageOptions: {
            ecmaVersion: 2020,
            sourceType: 'module',
            globals: {
                chrome: 'readonly',
                logger: 'readonly',
                self: 'readonly',
                globalThis: 'readonly',
                SpeechSynthesisUtterance: 'readonly',
                speechSynthesis: 'readonly',
                AudioContext: 'readonly',
                webkitAudioContext: 'readonly',
                importScripts: 'readonly',
                confirm: 'readonly',
                fetch: 'readonly',
                performance: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                Blob: 'readonly',
                URL: 'readonly',
                FileReader: 'readonly',
                alert: 'readonly',
                document: 'readonly',
                window: 'readonly',
                navigator: 'readonly',
                location: 'readonly',
                getCaseWord: 'readonly',
                getNumberWord: 'readonly',
                formatTime: 'readonly',
                SOUND_LIBRARY: 'readonly',
                GROUP_SOUND_LIBRARY: 'readonly',
                CONFIG: 'readonly',
                SHARED_CONSTANTS: 'readonly',
                APP_CONFIG: 'readonly',
                startAutoRestartTimer: 'readonly',
                stopAutoRestartTimer: 'readonly',
                generateUpdateBat: 'readonly',
                updateModalNotificationType: 'readonly',
                Event: 'readonly',
                require: 'readonly',
                module: 'readonly',
                __dirname: 'readonly',
            },
        },
        rules: {
            'no-unused-vars': ['warn', { args: 'none' }],
            'no-console': 'off',
            'prefer-const': 'warn',
            'no-empty': ['warn', { allowEmptyCatch: true }],
        },
    },
];
